import type { Mask, Pack } from "./types";

const now = () => new Date();

export const masks: Mask[] = [
  {
    mask_id: "1",
    generation: 1,
    name: "Hau",
    base_rarity: "RARE",
    buff_type: "PACK_STACKING",
    buff_base_value: 1,
    max_level: 5,
    description: "Great Mask of Shielding allowing larger storage of packs",
    original_color: "red",
    origin: "Toa Tahu",
    maskOffsetY: -10,
  },
  {
    mask_id: "2",
    generation: 1,
    name: "Kaukau",
    base_rarity: "RARE",
    buff_type: "DISCOVERY",
    buff_base_value: 0.1,
    max_level: 5,
    description: "Great Mask of Water Breathing with discovery boost",
    transparent: true,
    original_color: "blue",
    origin: "Toa Gali",
    maskOffsetY: -10,
  },
  {
    mask_id: "3",
    generation: 1,
    name: "Miru",
    base_rarity: "RARE",
    buff_type: "PROTODERMIS",
    buff_base_value: 0.1,
    max_level: 5,
    description: "Great Mask of Levitation with protodermis gain boost",
    original_color: "green",
    origin: "Toa Lewa",
    maskOffsetY: -12,
  },
  {
    mask_id: "4",
    generation: 1,
    name: "Kakama",
    base_rarity: "RARE",
    buff_type: "CD_REDUCTION",
    buff_base_value: 0.1,
    max_level: 5,
    description: "Great Mask of Speed with cooldown reduction",
    original_color: "brown",
    origin: "Toa Pohatu",
    maskOffsetY: -16,
  },
  {
    mask_id: "5",
    generation: 1,
    name: "Akaku",
    base_rarity: "RARE",
    buff_type: "INSPECTION",
    buff_base_value: 0.1,
    max_level: 5,
    description:
      "Great Mask of X-Ray vision with ability to inspect packs before opening",
    original_color: "white",
    origin: "Toa Kapaka",
    maskOffsetY: -10,
  },
  {
    mask_id: "6",
    generation: 1,
    name: "Pakari",
    base_rarity: "RARE",
    buff_type: "RARITY_ODDS",
    buff_base_value: 0.1,
    max_level: 5,
    description: "Great Mask of Strength empowering improved rarity odds.",
    original_color: "black",
    origin: "Toa Onua",
    maskOffsetY: -10,
  },
  {
    mask_id: "7",
    generation: 1,
    name: "Huna",
    base_rarity: "COMMON",
    buff_type: "COLOR_VARIANTS",
    buff_base_value: .01,
    max_level: 10,
    description: "Noble Mask of Concealment increasing discovery of color variants.",
    original_color: "orange",
    origin: "Turaga Vakama",
    maskOffsetY: -6,
  },
  {
    mask_id: "8",
    generation: 1,
    name: "Rau",
    base_rarity: "COMMON",
    buff_type: "PROTODERMIS",
    buff_base_value: .02,
    max_level: 10,
    description:
      "Noble Mask of Translation increasing protodermis gain.",
    original_color: "perriwinkle",
    origin: "Turaga Nokama",
    maskOffsetY: -14,
  },
  {
    mask_id: "9",
    generation: 1,
    name: "Mahiki",
    base_rarity: "COMMON",
    buff_type: "CD_REDUCTION",
    buff_base_value: .01,
    max_level: 10,
    description: "Noble Mask of Illusion reducing pack cooldown.",
    original_color: "lime",
    origin: "Turaga Matau",
    maskOffsetY: -16,
  },
  {
    mask_id: "10",
    generation: 1,
    name: "Komau",
    base_rarity: "COMMON",
    buff_type: "RARITY_ODDS",
    buff_base_value: .01,
    max_level: 10,
    description: "Noble Mask of Mind Control empowering improved rarity odds.",
    original_color: "tan",
    origin: "Turaga Onewa",
    maskOffsetY: -14,
  },
  {
    mask_id: "11",
    generation: 1,
    name: "Ruru",
    base_rarity: "COMMON",
    buff_type: "DISCOVERY",
    buff_base_value: .01,
    max_level: 10,
    description: "Noble Mask of Night Vision empowering mask discovery.",
    original_color: "dark gray",
    origin: "Turaga Whenua",
    maskOffsetY: -16,
  },
  {
    mask_id: "12",
    generation: 1,
    name: "Matatu",
    base_rarity: "COMMON",
    buff_type: "PACK_STACKING",
    buff_base_value: .5,
    max_level: 10,
    description: "Noble Mask of Telekenisis allowing a larger storage of packs.",
    original_color: "white",
    origin: "Turaga Nuju",
    maskOffsetY: -14,
  },
  {
    mask_id: "13",
    generation: 1,
    name: "Vahi",
    base_rarity: "MYTHIC",
    buff_type: "FRIEND_BONUS",
    buff_base_value: 0.2,
    max_level: 15,
    description: "The Legendary Mask of Time boosting friend benefits.",
    original_color: "gold",
    origin: "Toa Metru Vakama",
  },
];

export const packs: Pack[] = [
  {
    pack_id: "free_daily_v1",
    name: "Daily Pack",
    masks_per_pack: 2,
    guaranteed_min_rarity_floor: "COMMON",
    featured_generation: 1,
    created_at: now(),
  },
];
